variables:
  PUBLIC_URL: "/ndmvr-aframe/" # slash is important

image: node:22.11.0

stages:
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
    prefix: npm
  paths:
    - node_modules/

pages:
  stage: deploy
  tags:
    - ndmspc-hosted
  script:
    - npm install
    - npm run build -- --mode pages --base=$PUBLIC_URL
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish:
  stage: deploy
  image: node:22.11.0
  tags:
    - gitlab-org-docker
  id_tokens:
    NPM_ID_TOKEN:
      aud: "npm:registry.npmjs.org"
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - "sed -i -e 's/^  \\\"version\\\".*/  \\\"version\\\": \\\"'${CI_COMMIT_REF_NAME/v/}'\\\",/g' package.json"
    - npm config set legacy-peer-deps=true
    - npm install -g npm@latest
    - CI=true npm install
    - CI=true npm run build
    - export MY_VER_RELEASE=$(echo ${CI_COMMIT_REF_NAME/v/} | cut -sd '-' -f2)
    - if [ -z "$MY_VER_RELEASE" ];then CI=true npm publish --access public; fi
    - if [ -n "$MY_VER_RELEASE" ];then CI=true npm publish --access public --tag rc; fi
  only:
    - tags
